// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2993ym6cVReo8QAlAty_vgacLsonbnNg',
    appId: '1:1053977467748:web:10a03c7abd9f29e7e9b871',
    messagingSenderId: '1053977467748',
    projectId: 'smartserve-e7890',
    authDomain: 'smartserve-e7890.firebaseapp.com',
    storageBucket: 'smartserve-e7890.firebasestorage.app',
    measurementId: 'G-01GF1VRL38',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3gkR-YroiVp6nWCZZASFGl8gKMSj1l6g',
    appId: '1:1053977467748:android:53516b92efcc59d9e9b871',
    messagingSenderId: '1053977467748',
    projectId: 'smartserve-e7890',
    storageBucket: 'smartserve-e7890.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfR1AVywpREBM2NIp6LjV0DLIdbiDf39M',
    appId: '1:1053977467748:ios:9ea5ee3da9aaeb52e9b871',
    messagingSenderId: '1053977467748',
    projectId: 'smartserve-e7890',
    storageBucket: 'smartserve-e7890.firebasestorage.app',
    iosBundleId: 'com.example.smartserve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfR1AVywpREBM2NIp6LjV0DLIdbiDf39M',
    appId: '1:1053977467748:ios:9ea5ee3da9aaeb52e9b871',
    messagingSenderId: '1053977467748',
    projectId: 'smartserve-e7890',
    storageBucket: 'smartserve-e7890.firebasestorage.app',
    iosBundleId: 'com.example.smartserve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2993ym6cVReo8QAlAty_vgacLsonbnNg',
    appId: '1:1053977467748:web:24c9c0fdac14d966e9b871',
    messagingSenderId: '1053977467748',
    projectId: 'smartserve-e7890',
    authDomain: 'smartserve-e7890.firebaseapp.com',
    storageBucket: 'smartserve-e7890.firebasestorage.app',
    measurementId: 'G-71ZYV18RFC',
  );

}